package se.stagehand.lib.scripting

import scala.xml._

/**
 * The player part of an effect. Reads instructions generated by the EditorComponent
 * and executes them.
 */
trait PlayerComponent {

  /**
   * Load instructions for the player. 
   */
  def readInstructions(in: Elem)
  
  /**
   * Execute the given instructions over the assigned targets. TODO: How to define
   * targets for the effect. 
   */
  def executeInstructions: Unit
}